### ISSUE TITLE
[Bug Report]: github action does not run due to incompatible python dependency

### ISSUE THREAD

**Issue by mbaneryd** [microsoft/gpt-review#180]
### Module path

gpt github review

### review-gpt CLI version

0.9.4

### Describe the bug

The workflow fails when running the `Run source .env/bin/activate` sub step in `Run microsoft/gpt-review@v0.9.4` with this error

```
<module>
    info_str=example_info.json(indent=4),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/.../.env/lib/python3.11/site-packages/typing_extensions.py", line 2562, in wrapper
    return __arg(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/.../.env/lib/python3.11/site-packages/pydantic/main.py", line 952, in json
Error:     raise TypeError('`dumps_kwargs` keyword arguments are no longer supported.')
TypeError: `dumps_kwargs` keyword arguments are no longer supported.
Error: Process completed with exit code 1.
```

### To reproduce

Add this worklow to the repository

```
name: GPT Review on Pull Request

on:
  pull_request_target

jobs:
  add_pr_comment:
    runs-on: ubuntu-latest
    name: Azure OpenAI PR Comment
    steps:
      - id: review
        uses: microsoft/gpt-review@v0.9.4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AZURE_OPENAI_API: ${{ secrets.AZURE_OPENAI_API }}
          AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
```

### Relevant log output

```Shell
Collecting openapi-schema-pydantic<2.0,>=1.2 (from langchain>=0.0.154->llama-index<=0.6.9,>=0.6.0->gpt-review)
  Downloading openapi_schema_pydantic-1.2.4-py3-none-any.whl (90 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.0/90.0 kB 32.2 MB/s eta 0:00:00
Collecting pydantic<3,>=1 (from langchain>=0.0.154->llama-index<=0.6.9,>=0.6.0->gpt-review)
  Obtaining dependency information for pydantic<3,>=1 from https://files.pythonhosted.org/packages/82/54/ed9a1005c580b619a4c53c324f472c99c165051b22f8885b09be1882aece/pydantic-2.2.0-py3-none-any.whl.metadata
  Downloading pydantic-2.2.0-py3-none-any.whl.metadata (145 kB)
...

<module>
    info_str=example_info.json(indent=4),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/.../.env/lib/python3.11/site-packages/typing_extensions.py", line 2562, in wrapper
    return __arg(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/.../.env/lib/python3.11/site-packages/pydantic/main.py", line 952, in json
Error:     raise TypeError('`dumps_kwargs` keyword arguments are no longer supported.')
TypeError: `dumps_kwargs` keyword arguments are no longer supported.
Error: Process completed with exit code 1.
```
```
