### ISSUE TITLE
[Bug Report]: No comment on PR after workflow run succeeds

### ISSUE THREAD

**Issue by PratikGarai** [microsoft/gpt-review#211]
### Module path

gpt review

### review-gpt CLI version

0.9.5

### Describe the bug

Since there was a dependency issue #208  breaking the workflow, I created a copy of the ``action.yml`` file in my repository. I edited the file to add the install command as proposed by [this solution on the same issue](https://github.com/microsoft/gpt-review/issues/208#issuecomment-1763654379) and use this as my workflow.

The workflow runs successfully, but no changes are seen on the PR. No comments or reviews are created.

### To reproduce

1. Create a workflow in the existing repo
2. Add the following contents shown in code snippet
```yml
name: GPT Review on Pull Request

on:
  pull_request_target:
    branches: [ 'main' ]
 
jobs:
  add_pr_comment:
    runs-on: ubuntu-latest
    environment: <environment name> 
    name: Azure OpenAI PR Comment
    steps:
        - uses: actions/checkout@v3
          with:
            ref: ${{ github.event.pull_request.head.sha }}
            fetch-depth: 2
  
        - name: Set up Python 3.11
          uses: actions/setup-python@v4
          with:
            python-version: 3.11
  
        - name: Install gpt-review with fixed dependencies
          shell: bash
          run: |
            sudo apt-get update
            python3 -m venv .env
            source .env/bin/activate
            python -m pip install --upgrade pip
            python -m pip install langchain==0.0.301
            python -m pip install pydantic==1.10.13
            python -m pip install gpt-review==v0.9.5

        - name: Populate azure.yaml from vars
          env:
            AZURE_YAML: ${{ vars.AZURE_YAML }}
          shell: bash
          run: |
            echo "$AZURE_YAML" > azure.yaml
  
        - name: Review PR and make comment
          shell: bash
          run: |
            source .env/bin/activate
  
            gpt github review \
              --access-token $GITHUB_TOKEN \
              --pull-request $PATCH_PR \
              --repository $PATCH_REPO
          env:
            ACTION_REF: ${{ github.action_ref || env.BRANCH }}
            GIT_COMMIT_HASH: ${{ github.event.pull_request.head.sha }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            LINK: "https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}"
            PR_TITLE: ${{ github.event.pull_request.title }}
            BRANCH:  ${{ env.BRANCH }}
            AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY || '' }}
            AZURE_OPENAI_API: ${{ secrets.AZURE_OPENAI_API || '' }}
            PATCH_PR: ${{ github.event.pull_request.number }}
            PATCH_REPO: ${{ github.repository }}
            FULL_SUMMARY: true
            FILE_SUMMARY: false
            TEST_SUMMARY: false
            BUG_SUMMARY: false
            RISK_SUMMARY: false
            RISK_BREAKING: false
```
4. Create a PR on the repo
5. The workflow triggers, succeeds (screenshot below)
![image](https://github.com/microsoft/gpt-review/assets/58355527/ff3f1b2d-3c8a-4635-bc57-946ede6436fe)
6. No comment is seen in the original PR
