### ISSUE TITLE
Configure Azure Open AI models via configuration 

### ISSUE THREAD

**Issue by dciborow** [microsoft/gpt-review#45]
Right now we assume the engines are named gpt-35-turbo, gpt-4, or gpt-4-32k. We should use a file to configure this, following the format of Auto-GPT.

```
azure_api_type: azure
azure_api_base: https://synapseml-openai.openai.azure.com/
azure_api_version: 2023-03-15-preview
azure_model_map:
    turbo_llm_model_deployment_id: gpt-35-turbo
    smart_llm_model_deployment_id: gpt-4
    large_llm_model_deployment_id: gpt-4-32k
    embedding_model_deployment_id: text-embedding-ada-002

```
